### ISSUE TITLE
DIV0 error in validation

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#212]
DIV0 error in validation when searching for numeric outliers and there are no non-zero values in the columns. See https://humanitarian.atlassian.net/browse/HDX-6359

- [x] reproduce bug with unittest
- [x] fix bug
- [x] deploy to beta Proxy
- [x] update Jira issue
- [x] have dev team test and confirm fixed
- [x] finish Jira issue

Attn @danmihaila @alexandru-m-g @cjhendrix

**Comment by davidmegginson** [comment]
Test link (currently fails): https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Ffeature-data.humdata.org%2Fdataset%2Facled-data-for-united-arab-emirates

**Comment by davidmegginson** [comment]
```
mod_wsgi (pid=1178): Exception occurred processing WSGI script '/home/david/Source/HXL/hxl-proxy/hxl-proxy.wsgi'.
Traceback (most recent call last):
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/david/Source/HXL/hxl-proxy/hxl_proxy/reverse_proxied.py", line 43, in __call__
    return self.app(environ, start_response)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/david/Source/HXL/hxl-proxy/hxl_proxy/controllers.py", line 363, in data_validate
    schema_source
  File "/home/david/Source/HXL/libhxl-python/hxl/validation.py", line 1522, in validate
    status = hxl.schema(schema, callback=add_issue).validate(hxl.data(data))
  File "/home/david/Source/HXL/libhxl-python/hxl/validation.py", line 1188, in validate
    self.end_scan()
  File "/home/david/Source/HXL/libhxl-python/hxl/validation.py", line 1236, in end_scan
    rule.end_scan()
  File "/home/david/Source/HXL/libhxl-python/hxl/validation.py", line 1089, in end_scan
    test.end_scan()
  File "/home/david/Source/HXL/libhxl-python/hxl/validation.py", line 944, in end_scan
    self.variation_coefficients[tagspec] = self.standard_deviations[tagspec] / self.mean_values[tagspec]
 ZeroDivisionError: float division by zero
```

**Comment by davidmegginson** [comment]
Fixed (with unittest) and deployed to beta. Test link now works: https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Ffeature-data.humdata.org%2Fdataset%2Facled-data-for-united-arab-emirates

**Comment by davidmegginson** [comment]
Waiting for @alexandru-m-g or @danmihaila to test.

**Comment by danmihaila** [comment]
tested with https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Ftest-data.humdata.org%2Fdataset%2F4c13ed87-773b-452f-9326-32e78280890e%2Fresource%2Fa708d1c3-16ce-481e-8486-ceab8268e100%2Fdownload%2Ffts_requirements_funding_arg.csv and it is ok.
@davidmegginson we can close it and I will test on feature-data the next hxl proxy version when ready
