### ISSUE TITLE
Error in int() casting

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#214]
Reported in https://humanitarian.atlassian.net/browse/HDX-6370

- [x] reproduce bug with unit test
- [x] fix bug
- [x] deploy to beta proxy
- [x] update Jira issue
- [x] dev team tests and confirms OK
- [x] finish Jira issue

From @danmihaila :
>I deployed on https://feature-tools.humdata.org/wizard/#quickcharts the hxl proxy 1.13.1
data source url: http://proxy.hxlstandard.org/data.csv?url=http%3A//popstats.unhcr.org/en/asylum_seekers_monthly.hxl&filter01=select&select-query01-01=%23country%2Borigin=Hungary

>cookbook: https://raw.githubusercontent.com/OCHA-DAP/hxl-recipes/master/cookbook-libraries/unhcr-cookbook-library.json

> quick charts call is [here](https://feature-tools.humdata.org/quickcharts/app/show;url=http:%2F%2Fproxy.hxlstandard.org%2Fdata.csv%3Furl%3Dhttp%253A%2F%2Fpopstats.unhcr.org%2Fen%2Fasylum_seekers_monthly.hxl&filter01%3Dselect&select-query01-01%3D%2523country%252Borigin%3DHungary;embeddedSource=undefined;embeddedUrl=undefined;embeddedDate=undefined;embeddedConfig=%7B%22configVersion%22:4,%22bites%22:%5B%7B%22tempShowSaveCancelButtons%22:false,%22ingredient%22:%7B%22aggregateColumn%22:%22%23date%2Bmonth%22,%22valueColumn%22:%22%23affected%22,%22aggregateFunction%22:%22sum%22,%22dateColumn%22:null,%22comparisonValueColumn%22:null,%22comparisonOperator%22:null,%22filters%22:%7B%22filterWith%22:%5B%7B%22%23date%2Byear%22:%22$MAX$%22%7D%5D%7D,%22title%22:%22Total%20new%20asylum%20seekers%20by%20month%20%28latest%20year%29%22,%22description%22:%22%22%7D,%22type%22:%22chart%22,%22errorMsg%22:null,%22computedProperties%22:%7B%22pieChart%22:false,%22dataTitle%22:%22Value%22%7D,%22uiProperties%22:%7B%22swapAxis%22:true,%22showGrid%22:false,%22color%22:%22%231ebfb3%22,%22sortingByValue1%22:%22DESC%22,%22sortingByCategory1%22:null,%22internalColorPattern%22:%5B%22%231ebfb3%22,%22%230077ce%22,%22%23f2645a%22,%22%239C27B0%22%5D%7D,%22dataProperties%22:%7B%7D,%22displayCategory%22:%22Charts%22,%22hashCode%22:399741634%7D%5D%7D;singleWidgetMode=true;embeddedTitle=Quick%20Charts;recipeUrl=https:%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Fhxl-recipes%2F1.0.7%2Fcookbook-library.json;sample=false;chartSettings=true;chartShare=true)

> Call to hxl proxy is [here](https://feature-tools.humdata.org/hxlproxy/data.json?url=http%3A%2F%2Fproxy.hxlstandard.org%2Fdata.csv%3Furl%3Dhttp%253A%2F%2Fpopstats.unhcr.org%2Fen%2Fasylum_seekers_monthly.hxl%26filter01%3Dselect%26select-query01-01%3D%2523country%252Borigin%3DHungary&recipe=%5B%7B%22filter%22%3A%22with_rows%22%2C%22queries%22%3A%5B%22%23date%2Byear%3D2018%22%5D%7D%2C%7B%22filter%22%3A%22count%22%2C%22patterns%22%3A%5B%22%23date%2Bmonth%22%5D%2C%22aggregators%22%3A%5B%22sum(%23affected)%20as%20%23affected%22%5D%7D%2C%7B%22filter%22%3A%22sort%22%2C%22tags%22%3A%22%23date%2Bmonth%22%2C%22reverse%22%3Atrue%7D%5D)

> Message:

> ``{{error	"TypeError"``
> ``  message	"int() argument must be a string, a bytes-like object or a number, not 'NoneType'"``
> ``status	500}}``

> Screenshot with params attached also.

> I mention that on production the quick charts (all layers) are ok - https://data.humdata.org/dataset/unhcr-asylum-seekers-originating-hun

attn @danmihaila @alexandru-m-g

**Comment by davidmegginson** [comment]
```
mod_wsgi (pid=1176): Exception occurred processing WSGI script '/home/david/Source/HXL/hxl-proxy/hxl-proxy.wsgi'.
Traceback (most recent call last):
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/david/Source/HXL/hxl-proxy/hxl_proxy/reverse_proxied.py", line 43, in __call__
    return self.app(environ, start_response)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask_Cache-0.13.1-py3.6.egg/flask_cache/__init__.py", line 297, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/david/Source/HXL/hxl-proxy/hxl_proxy/controllers.py", line 470, in data_view
    result = get_result()
  File "/home/david/Source/HXL/hxl-proxy/hxl_proxy/controllers.py", line 457, in get_result
    response = flask.Response(list(source.gen_json(show_headers=show_headers, use_objects=use_objects)), mimetype='application/json')
  File "/home/david/Source/HXL/libhxl-python/hxl/model.py", line 614, in gen_json
    for raw in self.gen_raw(show_headers, show_tags):
  File "/home/david/Source/HXL/libhxl-python/hxl/model.py", line 581, in gen_raw
    for row in self:
  File "/home/david/Source/HXL/libhxl-python/hxl/filters.py", line 394, in __next__
    self.outer._saved_rows = self.outer.filter_rows()
  File "/home/david/Source/HXL/libhxl-python/hxl/filters.py", line 2278, in filter_rows
    return sorted(self.source.values, key=make_key, reverse=self.reverse)
  File "/home/david/Source/HXL/libhxl-python/hxl/filters.py", line 2276, in make_key
    return self._make_key(indices, values)
  File "/home/david/Source/HXL/libhxl-python/hxl/filters.py", line 2305, in _make_key
    key.append(SortFilter._make_sort_value(self.columns[index].tag, value))
  File "/home/david/Source/HXL/libhxl-python/hxl/filters.py", line 2322, in _make_sort_value
    return (float('inf'), hxl.datatypes.normalise_date(norm))
  File "/home/david/Source/HXL/libhxl-python/hxl/datatypes.py", line 242, in normalise_date
    day=(date1.day if date1.day==date2.day else None)
  File "/home/david/Source/HXL/libhxl-python/hxl/datatypes.py", line 213, in make_date
    return '{:04d}-{:02d}'.format(int(year), int(month))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by davidmegginson** [comment]
Reproduced with unit test. The error comes when there is a month name like "July" but no year and the string gets passed to normalise_date(). 

Example dataset: http://proxy.hxlstandard.org/data.csv?url=http%3A//popstats.unhcr.org/en/asylum_seekers_monthly.hxl&filter01=select&select-query01-01=%23country%2Borigin=Hungary

**Comment by davidmegginson** [comment]
Appears to be fixed. Waiting to deploy to beta Proxy for dev-team testing (can't ssh to new IP; will get @teodorescuserban 's help tomorrow).

**Comment by davidmegginson** [comment]
Deployed to beta Proxy and tested successfully. [Confirmation link](https://beta.proxy.hxlstandard.org/data.json?url=http%3A%2F%2Fproxy.hxlstandard.org%2Fdata.csv%3Furl%3Dhttp%253A%2F%2Fpopstats.unhcr.org%2Fen%2Fasylum_seekers_monthly.hxl%26filter01%3Dselect%26select-query01-01%3D%2523country%252Borigin%3DHungary&recipe=%5B%7B%22filter%22%3A%22with_rows%22%2C%22queries%22%3A%5B%22%23date%2Byear%3D2018%22%5D%7D%2C%7B%22filter%22%3A%22count%22%2C%22patterns%22%3A%5B%22%23date%2Bmonth%22%5D%2C%22aggregators%22%3A%5B%22sum(%23affected)%20as%20%23affected%22%5D%7D%2C%7B%22filter%22%3A%22sort%22%2C%22tags%22%3A%22%23date%2Bmonth%22%2C%22reverse%22%3Atrue%7D%5D)

**Comment by davidmegginson** [comment]
Waiting for @danmihaila or @alexandru-m-g to test.

**Comment by danmihaila** [comment]
@davidmegginson I tested, it looks good. I will test again the hxl proxy version on tools. thank you

**Comment by davidmegginson** [comment]
Updating Jira issue and closing this one (we can reopen if any problems surface).
