### ISSUE TITLE
Local variable "row" referenced before assignment

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#215]
Discovered a bug, associated (probably) with the select or JSON filter.

[test link](https://beta.proxy.hxlstandard.org/data?url=https%3A%2F%2Fapi.hpc.tools%2Fv1%2Fpublic%2Fproject%2Fplancode%2FHAFG18&name=Mali+2019+HRP+Projects&tagger-match-all=on&tagger-02-header=code&tagger-02-tag=%23activity%2Bcode&tagger-03-header=implementationstatus&tagger-03-tag=%23status&tagger-10-header=name&tagger-10-tag=%23activity%2Bname&tagger-11-header=objective&tagger-11-tag=%23description%2Bobjective&tagger-12-header=startdate&tagger-12-tag=%23date%2Bstart&tagger-13-header=enddate&tagger-13-tag=%23date%2Bend&tagger-14-header=currentrequestedfunds&tagger-14-tag=%23value%2Brequested%2Bcurrent%2Bc_usd&tagger-15-header=origrequestedfunds&tagger-15-tag=%23value%2Brequested%2Borig%2Bc_usd&tagger-16-header=cluster&tagger-16-tag=%23sector%2Bcluster&tagger-24-header=location&tagger-24-tag=%23loc&tagger-27-header=organization&tagger-27-tag=%23org+%2Bname&tagger-34-header=visible&tagger-34-tag=%23meta%2Bvisible&header-row=1&filter01=clean&clean-date-tags01=%23date&filter02=jsonpath&jsonpath-path02=name&jsonpath-patterns02=%23sector&filter03=jsonpath&jsonpath-path03=name&jsonpath-patterns03=%23loc&filter04=jsonpath&jsonpath-path04=name&jsonpath-patterns04=%23org&filter05=select&select-query05-01=%23meta%2Bvisible%3Dtrue&filter06=cut&cut-exclude-tags06=meta%2Bvisible&cut-skip-untagged06=on)

**Comment by davidmegginson** [comment]
Traceback:

```
mod_wsgi (pid=7613): Exception occurred processing WSGI script '/home/david/Source/HXL/hxl-proxy/hxl-proxy.wsgi'.
Traceback (most recent call last):
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/david/Source/HXL/hxl-proxy/hxl_proxy/reverse_proxied.py", line 43, in __call__
    return self.app(environ, start_response)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/david/.virtualenvs/proxy/lib/python3.6/site-packages/Flask_Cache-0.13.1-py3.6.egg/flask_cache/__init__.py", line 297, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/david/Source/HXL/hxl-proxy/hxl_proxy/controllers.py", line 470, in data_view
    result = get_result()
  File "/home/david/Source/HXL/hxl-proxy/hxl_proxy/controllers.py", line 432, in get_result
    source = filters.setup_filters(recipe)
  File "/home/david/Source/HXL/hxl-proxy/hxl_proxy/filters.py", line 42, in setup_filters
    source.columns
  File "/home/david/Source/HXL/libhxl-python/hxl/io.py", line 805, in columns
    self._columns = self._find_tags()
  File "/home/david/Source/HXL/libhxl-python/hxl/io.py", line 815, in _find_tags
    raw_row = self._get_row()
  File "/home/david/Source/HXL/libhxl-python/hxl/io.py", line 867, in _get_row
    return next(self._iter)
  File "/home/david/Source/HXL/libhxl-python/hxl/converters.py", line 66, in __next__
    if self._add_tags():
  File "/home/david/Source/HXL/libhxl-python/hxl/converters.py", line 82, in _add_tags
    raw_row = next(self.input)
  File "/home/david/Source/HXL/libhxl-python/hxl/io.py", line 670, in __next__
    return row
UnboundLocalError: local variable 'row' referenced before assignment
```

**Comment by davidmegginson** [comment]
The problem is that the tagger fails when there is no source data (e.g. an empty JSON array). The first step is eliminating the error (done), then it will be necessary to let the tagger return a better message.

**Comment by davidmegginson** [comment]
Closing this issue, and following up in #216 for better error reporting.
