### ISSUE TITLE
Bad keyword "encoding" for json.load

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#283]
Traceback (most recent call last):
  File "/home/david/Source/HXL/3wtest/parse.py", line 76, in <module>
    run(scan_data, sys.stdout)
  File "/home/david/Source/HXL/3wtest/parse.py", line 34, in run
    parse_dataset(output, scan_row, countries)
  File "/home/david/Source/HXL/3wtest/parse.py", line 39, in parse_dataset
    dataset = hxl.data(url, http_headers={"User-Agent": "HDX-Developer-2015"})
  File "/home/david/Source/HXL/3wtest/venv/lib/python3.9/site-packages/hxl/io.py", line 167, in data
    return HXLReader(make_input(
  File "/home/david/Source/HXL/3wtest/venv/lib/python3.9/site-packages/hxl/io.py", line 438, in make_input
    return JSONInput(input, selector=selector, encoding=encoding)
  File "/home/david/Source/HXL/3wtest/venv/lib/python3.9/site-packages/hxl/io.py", line 850, in __init__
    self.json_data = self._select(selector, json.load(_input, encoding=encoding, object_pairs_hook=collections.OrderedDict))
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by davidmegginson** [comment]
Already fixed by 4f1150656
