### ISSUE TITLE
Error in [ python run-server.py ]

### ISSUE THREAD

**Issue by ghost** [HXLStandard/libhxl-python#60]
sh-3.2# python run-server.py
Traceback (most recent call last):
  File "run-server.py", line 5, in <module>
    from hxl_proxy import app
  File "/Documents/hxl-proxy-master/hxl_proxy/**init**.py", line 39, in <module>
    import hxl_proxy.controllers
  File "/Documents/hxl-proxy-master/hxl_proxy/controllers.py", line 25, in <module>
    from hxl_proxy.util import get_profile, check_auth, make_data_url, make_cache_key, skip_cache_p, urlencode_utf8
  File "/Documents/hxl-proxy-master/hxl_proxy/util.py", line 148, in <module>
    urllib.parse.quote_plus
AttributeError: 'module' object has no attribute 'parse'

**Comment by davidmegginson** [comment]
Thanks for the report.  The HXL Proxy works only with Python3 right now, but I will look into making it work with Python2 if that's a requirement for you (libhxl-python itself already works with both).
