### ISSUE TITLE
tagger convenience method has import error

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#88]
Test script:

```
import hxl

for row in hxl.tagger('foo.xlsx', [], sheet_index=1, allow_local=True):
    print(row)
```
[foo.xlsx](https://github.com/HXLStandard/libhxl-python/files/1022603/foo.xlsx)

Error:

```
Traceback (most recent call last):
  File "test-tagger.py", line 3, in <module>
    for row in hxl.tagger('foo.xlsx', [], sheet_index=1, allow_local=True):
  File "/home/david/Source/HXL/libhxl-python/hxl/io.py", line 103, in tagger
    hxl.converters.Tagger(
AttributeError: module 'hxl' has no attribute 'converters'
```

**Comment by davidmegginson** [comment]
Bug fixed - test script now throws a HXLTagsNotFoundException, as expected.
